### ISSUE TITLE
EC12E_SW Encoder & Mouser

### ISSUE THREAD

**Issue by GRK-Astronomer** [Shayshez/DSO150-Euro-Scope#1]
Hi Shay,

I noticed the Encoder listeec in the BOM for the DSO 150 Euro Scope is definitely no specific enough to identify which of the Mouser Part Numbers match what needs to be purchased.  EC12E_SW is not a part number on Mouser or with Alps that makes the encoder needed.

Could tou be more specific on the exact part required.  I have ordered all parts for three of the DSO 150 Eurorack modules except for the encoder.

Thanks,

Glenn

**Comment by GRK-Astronomer** [comment]
Shay is working on this.  DSO150 needs to have an encoder with 30 detents.  Current one only has 20

Old 20 Detent: https://www.mouser.co.il/ProductDetail/858-EN11-HSM1BF20

Testing 30 Detent: https://www.mouser.co.il/ProductDetail/652-PEC11L4220FS0015

**Comment by Shayshez** [comment]
The Bourns 30 Detent encoder is perfect.
it is possible to solder it directly to DSO-150 Main board in this case it's better to use the 15mm shaft version:
https://www.mouser.co.il/ProductDetail/Bourns/PEC11L-4215F-S0015?qs=%2fha2pyFaduidMAYXvh4P%252bOYpJ3IdIhoUo8uIZ1WEUoAT7d1DMvSXvN1e3FrxHJAy

**Comment by GRK-Astronomer** [comment]
Hi Shay,

Thanks for the “construction” note regarding the Bourns encoder.  I will order the three that I need today.  The MA faceplate and interface board for one of the DSOs arrived yesterday and I am holding off on ordering the other two.  The remainder if the parts and the DSO-Kits were ordered already.  I imagine the DSO kits take awhile in the mail.

BTW, I liked the u_T and o_C combined 1U module idea.  I have them in separate 3U modules; but, have not had a lot of time to “explore” them yet.  Probably would have been better to look at them as Utility modules place into 1U format to begin with.  So, when things become available, I will probably get yours and set the others aside for awhile.

I want to say, THANK YOU, for the help you have been!

**Comment by GRK-Astronomer** [comment]
Closing the issue.
